# -*- coding: utf-8 -*-
"""Treino de Analise em PYTHON .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNXIe1JL7rL6uI9hy7diVV6AbRONHwv1
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv')

df.head(10)

df.info()
#aprendizado de informações de todas as colunas e quantidade de dados

df.describe(
)
#descrição rapida e geral dos dados que mais aparecem, max e min e em porcentagens

df.shape
#informa o formato da tabela, quantidade de colunas e linhas

va1, va2 = df.shape[0], df.shape[1]
print('linhas:', va1)
print('colunas:', va2)

#criação de uma vizualização das linhas e colunas de forma mais simples e clara
#criando variaveis

df.columns
#nomes das colunas

renomear_colunas = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': "usd",
    'employee_residence': "residencia",
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}
df.rename(columns=renomear_colunas, inplace=True)
df.columns

#renomear colunas e fazer a verificação da ação

df.columns

df['senioridade'].value_counts()
#mostra a quantidade da coluna selecionada

df['contrato'].value_counts()
#mostra a quantidade da coluna selecionada

df['remoto'].value_counts()
#mostra a quantidade da coluna selecionada

df['tamanho_empresa'].value_counts()
#mostra a quantidade da coluna selecionada

senioridade = {
    'SE': "senior",
    'MI': 'pleno',
    'EN': 'junior',
    'EX': 'executivo',
}

df['senioridade'] = df['senioridade'].replace(senioridade)
df['senioridade'].value_counts()

#renomear e verificar o nome das linhas da coluna selecionada

remoto = {
    0: 'presencial',
    50: 'hibrido',
    100: 'remoto',
}

df['remoto'] = df['remoto'].replace(remoto)
df['remoto'].value_counts()
#renomear e verificar o nome das linhas da coluna selecionada

tamanho_empresa = {
    'L': "grande",
    'M': 'media',
    'S': 'pequena',
}

df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)
df['tamanho_empresa'].value_counts()
#renomear e verificar o nome das linhas da coluna selecionada

df.head()
#demonstra a tabela de forma clara

contrato = {
    'FT': 'integral',
    'CT': 'contrato',
    'FL': 'freelance',
    'PT': 'parcial',
}
df['contrato'] = df['contrato'].replace(contrato)
df['contrato'].value_counts()

df.describe(include='object')
#mostra o valor que mais aparece nas colunas e a frequencia

#Qual o nível de experiência mais comum na base de dados?
#(Senior)
#Qual é o tipo de contrato mais frequente?
#(Integral)
#Qual o cargo mais frequente na amostra?
#(Cientista de Dados)
#De qual país são a maioria dos profissionais da base?
#(Estados Unidos)
#Qual é o país onde mais empresas da amostra estão sediadas?
#(Estados Unidos)
#Qual o regime de trabalho mais comum?
#(Presencial)
#Qual é o tamanho mais comum das empresas na amostra?
#(Media)

df.describe()

df.isnull()

df.head()

df.isnull().sum()

df['ano'].unique()
#nan = not a number

df[df.isnull().any(axis=1)]

import numpy as np

#criação de um dataframe de teste para usar de exemplo
df_salarios = pd.DataFrame({
    'nome': ('Ana', 'Bruno','Carlos', 'Daniele', 'Val'),
    'salario': (4000, np.nan, 5000, np.nan, 100000)

})

#calcula media e substitui os nulos pela media e arredonda os valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))

'''calcula mediana e substitui os nulos pela mediana

comentarios grandes

'''
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())
df_salarios

df_temperaturas = pd.DataFrame({
    'Dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas['preenchido_ffill'] = df_temperaturas['Temperatura'].ffill()
df_temperaturas

df_temperaturas = pd.DataFrame({
    'Dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas['preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

df.cidades = pd.DataFrame({
    'nome': ('Ana', 'Bruno','Carlos', 'Daniele', 'Val'),
    'cidade': ('São Paulo', np.nan, 'Curitiba', np.nan, "Belém")
})
df.cidades['cidade_preenchida'] = df.cidades['cidade'].fillna('Não informado')
df.cidades

df_limpo = df.dropna()
df_limpo.isnull().sum()

df_limpo.head()

df_limpo.info()

df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))

df_limpo.head()

df_limpo['senioridade'].value_counts().plot(kind='bar', title='Distribuição de senioridade')

import seaborn as sns

import matplotlib as plt
sns.barplot(data= df_limpo, x='senioridade', y='usd')

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.barplot(data= df_limpo, x='senioridade', y='usd')
plt.title('Salario medio por senioridade')
plt.xlabel('senioridade')
plt.ylabel('Salario medio anual (USD)')
plt.show()

df_limpo.groupby('senioridade')['usd'].mean().sort_values(ascending=False)

ordem = df_limpo.groupby('senioridade')['usd'].mean().sort_values(ascending=True).index

plt.figure(figsize=(8,5))
sns.barplot(data= df_limpo, x='senioridade', y='usd', order=ordem)
plt.title('Salario medio por senioridade')
plt.xlabel('senioridade')
plt.ylabel('Salario medio anual (USD)')
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(df_limpo['usd'], bins= 50, kde=True)
plt.title('Distribuição dos salários anuais')
plt.xlabel('Salário em USD')
plt.ylabel('Frequência')
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df_limpo['usd'])
plt.title('Distribuição dos salários anuais')
plt.xlabel('Salário em USD')
plt.show()

ordem_senioridade = ['junior','pleno','senior','executivo']

plt.figure(figsize=(8,5))
sns.boxplot(x='senioridade', y='usd', data=df_limpo, order=ordem_senioridade,)
plt.title('Distribuição por senioridade')
plt.xlabel('Salário em USD')
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='senioridade', y='usd', data=df_limpo, order=ordem_senioridade, palette='Set2', hue='senioridade')
plt.title('Distribuição por senioridade')
plt.xlabel('Salário em USD')
plt.show()

import plotly.express as px

df_senioridade_salario = df_limpo.groupby('senioridade')['usd'].mean().reindex(ordem_senioridade).reset_index()
fig = px.bar(df_senioridade_salario, x='senioridade', y='usd',
             title='Média Salarial por Senioridade (USD)',
             labels={'senioridade': 'Nível de Senioridade', 'usd': 'Média Salarial Anual (USD)'},
             color='senioridade', # Adiciona cores diferentes para cada nível de senioridade
             color_discrete_sequence=px.colors.qualitative.Set2)
fig.show()

remoto_contagem = df_limpo['remoto'].value_counts().reset_index()
remoto_contagem.columns = ['tipo_trabalho', 'quantidade']


fig = px.pie(remoto_contagem, names='tipo_trabalho',
             values='quantidade',
             title='Proporção dos Tipo de Trabalho',
             hole=0.5,



)
fig.update_traces(textinfo='percent+label')
fig.show()



import plotly.graph_objects as go

# Ensure df_cientista_dados and salario_por_pais are defined
df_cientista_dados = df_limpo[df_limpo['cargo'] == 'Data Scientist']
salario_por_pais = df_cientista_dados.groupby('empresa')['usd'].mean().sort_values(ascending=False).reset_index()

fig = go.Figure(data=[go.Table(
    header=dict(values=['País', 'Salário Médio Anual (USD)'],
                fill_color='paleturquoise',
                align='left'),
    cells=dict(values=[salario_por_pais['empresa'], salario_por_pais['usd'].round(2)],
               fill_color='lavender',
               align='left'))
])

fig.update_layout(title_text='Salário Médio para Cientista de Dados por País (Plotly Table)')
fig.show()